/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farmacia.view.Produtos;

import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class ProdutosCRUD extends javax.swing.JFrame {

    /**
     * Creates new form ProdutosdCRUD
     */
    public ProdutosCRUD() {
        initComponents();
        TextAreaDescricao.setLineWrap(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelNome = new javax.swing.JLabel();
        TextFieldNome = new javax.swing.JTextField();
        LabelID = new javax.swing.JLabel();
        TextFieldID = new javax.swing.JTextField();
        TextFieldValor = new javax.swing.JTextField();
        LabelDescricao = new javax.swing.JLabel();
        LabelValor = new javax.swing.JLabel();
        ComboBoxProdutos = new javax.swing.JComboBox<>();
        ButtonCadastra = new javax.swing.JButton();
        ButtonAltera = new javax.swing.JButton();
        ButtonExclui = new javax.swing.JButton();
        ButtonLimpa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaDescricao = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de produtos");
        setResizable(false);

        LabelNome.setText("Nome:");

        TextFieldNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextFieldNomeFocusLost(evt);
            }
        });

        LabelID.setText("ID:");

        TextFieldID.setEditable(false);

        TextFieldValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextFieldValorFocusLost(evt);
            }
        });

        LabelDescricao.setText("Descrição:");

        LabelValor.setText("Valor:");

        ComboBoxProdutos.setEditable(true);
        ComboBoxProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxProdutosActionPerformed(evt);
            }
        });

        ButtonCadastra.setText("Cadastra");

        ButtonAltera.setText("Altera");

        ButtonExclui.setText("Exclui");

        ButtonLimpa.setText("Limpar");

        TextAreaDescricao.setColumns(20);
        TextAreaDescricao.setRows(5);
        TextAreaDescricao.setWrapStyleWord(true);
        TextAreaDescricao.setBorder(null);
        TextAreaDescricao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextAreaDescricaoFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(TextAreaDescricao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelID)
                            .addComponent(LabelNome)
                            .addComponent(LabelDescricao)
                            .addComponent(LabelValor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(ComboBoxProdutos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(ButtonCadastra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonAltera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonExclui)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonLimpa)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelID)
                    .addComponent(TextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNome)
                    .addComponent(TextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelDescricao)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelValor)
                    .addComponent(TextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBoxProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCadastra)
                    .addComponent(ButtonAltera)
                    .addComponent(ButtonExclui)
                    .addComponent(ButtonLimpa))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxProdutosActionPerformed

    private void TextFieldValorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldValorFocusLost
        // TODO add your handling code here:
        if (TextFieldValor.isEditable()){
            if (TextAreaDescricao.getText().length()!= 0 && TextAreaDescricao.getText().length() < 251 ){
                if (TextFieldValor.getText().length() != 0){
                    if (ConverteVirgula(TextFieldValor.getText())== 0.0){
                        JOptionPane.showMessageDialog(this.TextFieldValor, "Campo Valor possui dados inválidos.","Valor", JOptionPane.ERROR_MESSAGE);
                        TextFieldValor.requestFocus();
                    }else {
                        double registra = ConverteVirgula(TextFieldValor.getText());
                        TextFieldValor.setText(String.valueOf(registra));                        
                    }
                }else {
                    JOptionPane.showMessageDialog(this.TextFieldValor, "Campo Valor esta vazio.","Valor", JOptionPane.ERROR_MESSAGE);
                    TextFieldValor.requestFocus();
                    }   
            }TextAreaDescricao.requestFocus();
             
        }
        
    }//GEN-LAST:event_TextFieldValorFocusLost

    private void TextFieldNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldNomeFocusLost
        // TODO add your handling code here:
        if (TextFieldNome.isEditable()){
            if (TextFieldNome.getText().length() != 0){
                if (matchesOnlyText(TextFieldValor.getText())){
                    JOptionPane.showMessageDialog(this.TextFieldNome, "Campo nome possui dados inválidos.","Nome", JOptionPane.ERROR_MESSAGE);
                    TextFieldNome.requestFocus();
                }
            }else{
                JOptionPane.showMessageDialog(this.TextFieldNome, "Campo nome esta vazio..","Nome", JOptionPane.ERROR_MESSAGE);
                TextFieldNome.requestFocus();
            }  
        }
    }//GEN-LAST:event_TextFieldNomeFocusLost

    private void TextAreaDescricaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextAreaDescricaoFocusLost
        // TODO add your handling code here:
        if (TextAreaDescricao.isEditable()){
            if (TextFieldNome.getText().length() != 0){
                if (TextAreaDescricao.getText().length() >= 251){
                    JOptionPane.showMessageDialog(this.TextAreaDescricao, "Campo Descriçãop maior que o esperado\n simplifique os dados informados.","Descrição muito grande", JOptionPane.ERROR_MESSAGE);
                    TextAreaDescricao.requestFocus();
                }else if(TextAreaDescricao.getText().length()== 0){
                    JOptionPane.showMessageDialog(this.TextAreaDescricao, "Campo Descrição esta vazio.","Descrição vazia", JOptionPane.ERROR_MESSAGE);
                    TextAreaDescricao.requestFocus();
                }
            }else TextFieldNome.requestFocus();
              
        }
    }//GEN-LAST:event_TextAreaDescricaoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutosCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutosCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutosCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutosCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutosCRUD().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAltera;
    private javax.swing.JButton ButtonCadastra;
    private javax.swing.JButton ButtonExclui;
    private javax.swing.JButton ButtonLimpa;
    private javax.swing.JComboBox<String> ComboBoxProdutos;
    private javax.swing.JLabel LabelDescricao;
    private javax.swing.JLabel LabelID;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JLabel LabelValor;
    private javax.swing.JTextArea TextAreaDescricao;
    private javax.swing.JTextField TextFieldID;
    private javax.swing.JTextField TextFieldNome;
    private javax.swing.JTextField TextFieldValor;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    public double ConverteVirgula(String valor){
        String replace = valor.replace(",",".");
        try{
            return Double.parseDouble(replace);
        }catch(NumberFormatException e){
            return 0.0 ;
        }
    }
    public String ConvertePonto(double valor){
        String replace = Double.toString(valor);
         return replace = replace.replace(".",",");
    }    
    public boolean matchesOnlyText(String text) {
        return text.matches("[A-Z_a-z_À-ú\\s\\p{L}]+");
    }
    

}
