/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package farmacia.view.Funcionario;
import model.Funcionario;
import java.util.Date;
import java.lang.String;
import java.util.Random;


/**
 *
 * @author Alvaro Pereira do Nascimento
 */
public class FuncionarioCRUD extends javax.swing.JFrame {

    /**
     * Creates new form FuncionárioCRUD
     */
    public FuncionarioCRUD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        LabelNomeUsuario = new javax.swing.JLabel();
        TextFieldNomeUsuario = new javax.swing.JTextField();
        TextFieldNome = new javax.swing.JTextField();
        LabelNome = new javax.swing.JLabel();
        LabelDataAdmissao = new javax.swing.JLabel();
        jFormattedDataAdimissao = new javax.swing.JFormattedTextField();
        LabelSalario = new javax.swing.JLabel();
        TextFieldSalario = new javax.swing.JTextField();
        ButtonCadastra = new javax.swing.JButton();
        ButtonAlterar = new javax.swing.JButton();
        ButtonExcluir = new javax.swing.JButton();
        ButtonConsulta = new javax.swing.JButton();
        RadioButtonFuncionario = new javax.swing.JRadioButton();
        RadioButtonGerente = new javax.swing.JRadioButton();
        LabelSenha = new javax.swing.JLabel();
        PasswordFieldSenha = new javax.swing.JPasswordField();
        btnRandom = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelNomeUsuario.setText("Nome do Usuário:");

        LabelNome.setText("Nome:");

        LabelDataAdmissao.setText("Data de admissão:");

        LabelSalario.setText("Salário:");

        TextFieldSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldSalarioActionPerformed(evt);
            }
        });

        ButtonCadastra.setText(" Cadastrar");
        ButtonCadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCadastraActionPerformed(evt);
            }
        });

        ButtonAlterar.setText("Alterar");
        ButtonAlterar.setToolTipText("");

        ButtonExcluir.setText("Excluir");
        ButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonExcluirActionPerformed(evt);
            }
        });

        ButtonConsulta.setText("Consulta");
        ButtonConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConsultaActionPerformed(evt);
            }
        });

        RadioButtonFuncionario.setText("Funcionário");

        RadioButtonGerente.setText("Gerente");

        LabelSenha.setText("Senha:");

        PasswordFieldSenha.setText("jPasswordField1");

        btnRandom.setText("( )");
        btnRandom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRandomMouseClicked(evt);
            }
        });

        jLabel1.setText("Random");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(ButtonCadastra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonAlterar)
                .addGap(18, 18, 18)
                .addComponent(ButtonExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonConsulta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelSalario)
                            .addComponent(LabelDataAdmissao)
                            .addComponent(LabelNomeUsuario)
                            .addComponent(LabelNome)
                            .addComponent(LabelSenha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TextFieldNome, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                        .addComponent(TextFieldNomeUsuario))
                                    .addComponent(TextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedDataAdimissao, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(RadioButtonFuncionario)
                        .addGap(18, 18, 18)
                        .addComponent(RadioButtonGerente)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRandom)
                    .addComponent(jLabel1))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNomeUsuario)
                    .addComponent(TextFieldNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDataAdmissao)
                    .addComponent(jFormattedDataAdimissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelSalario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelSenha)
                    .addComponent(PasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RadioButtonFuncionario)
                            .addComponent(RadioButtonGerente)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonCadastra)
                            .addComponent(ButtonAlterar)
                            .addComponent(ButtonExcluir)
                            .addComponent(ButtonConsulta))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldSalarioActionPerformed

    private void ButtonCadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCadastraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonCadastraActionPerformed

    private void ButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonExcluirActionPerformed

    private void ButtonConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonConsultaActionPerformed

    private void btnRandomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRandomMouseClicked
       
        String[] nomes = new String[10];
        nomes[1] = "Steci";
        nomes[2] = "Emanuela";
        nomes[3] = "Antoni";
        nomes[4] = "Luciano";
        nomes[5] = "Vitoria";
        nomes[6] = "Henrique";
        nomes[7] = "Renata";
        nomes[8] = "Andressa";
        nomes[9] = "Hugo";
        nomes[10] = "Roseli";
        
        String[] datas = new String[10];
        datas[1] = "01/01/2000";
        datas[2] = "10/03/2003";
        datas[3] = "27/02/2003";
        datas[4] = "19/10/1968";
        datas[5] = "14/09/2012";
        datas[6] = "01/01/2002";
        datas[7] = "05/10/2003";
        datas[8] = "17/06/1998";
        datas[9] = "19/06/1998";
        datas[10] = "08/07/2003";
        
        double[] salarios = new double[10];
        salarios[1] = 123.12;
        salarios[2] = 620.12;
        salarios[3] = 720.99;
        salarios[4] = 870.50;
        salarios[5] = 1500.00;
        salarios[6] = 1192.50;
        salarios[7] = 920.79;
        salarios[8] = 250.30;
        salarios[9] = 100.10;
        salarios[10] = 1700.00;
        
        String senha = "123";
        
        Random gerador = new Random();
        
        int x  = gerador.nextInt(11);
        TextFieldNome.setText(nomes[x]);
        
        x  = gerador.nextInt(11);
        jFormattedDataAdimissao.setText(datas[x]);
        
        x  = gerador.nextInt(11);
        TextFieldNomeUsuario.setText(nomes[x]);
        
        x  = gerador.nextInt(11);
        TextFieldSalario.setText(""+salarios[x]);
        
        x  = gerador.nextInt(11);
        PasswordFieldSenha.setText(senha);
        
        if((x % 2) == 0){
            RadioButtonFuncionario.doClick();
        }else{
            RadioButtonGerente.doClick();
        }
        
    }//GEN-LAST:event_btnRandomMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncionarioCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncionarioCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncionarioCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncionarioCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuncionarioCRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAlterar;
    private javax.swing.JButton ButtonCadastra;
    private javax.swing.JButton ButtonConsulta;
    private javax.swing.JButton ButtonExcluir;
    private javax.swing.JLabel LabelDataAdmissao;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JLabel LabelNomeUsuario;
    private javax.swing.JLabel LabelSalario;
    private javax.swing.JLabel LabelSenha;
    private javax.swing.JPasswordField PasswordFieldSenha;
    private javax.swing.JRadioButton RadioButtonFuncionario;
    private javax.swing.JRadioButton RadioButtonGerente;
    private javax.swing.JTextField TextFieldNome;
    private javax.swing.JTextField TextFieldNomeUsuario;
    private javax.swing.JTextField TextFieldSalario;
    private javax.swing.JButton btnRandom;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField jFormattedDataAdimissao;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
